services:
  crawling:
    image: wa6221/ajouevent-crawling:latest
    container_name: ajouevent-crawling
    restart: always
    env_file:
      - .env
    ports:
      - "1323:1323"
    networks:
      - ajouevent-network
    logging:
      driver: loki
      options:
        loki-url: http://127.0.0.1:3100/loki/api/v1/push
        loki-external-labels: service=ajouevent-crawling,container_name=ajouevent-crawling

networks:
  ajouevent-network:
    external: true
    name: ajouevent_ajouevent-network
